### PR TITLE
Split GUIControl into a base class ClassicSimConrol and a subclass GUIControl

### PR DESCRIPTION
**Pull request by jokal2**
See #252.

This would just be a demonstration of concept of the first step. Further patches will move anything that doesn't care about GUIs from the ClassicSimControl -> GUIControl.

### CODE REVIEW

**Comment by jokal2** [comment]
@timhul Any comment on this idea? If this idea is approved I'd like to start fleshing out the CLI version. But this is a hard blocker.

**Comment by timhul** [comment]
@jokal2 I'm not sure that this is a necessary entry point for a CLI as this covers much more functionality than necessary. I described what the minimal program loop is (or should be) for a CLI in [this comment](https://github.com/timhul/ClassicSim/issues/145#issuecomment-588540030 ), did you encounter issues with this approach?

**Comment by timhul** [comment]
> I'm not sure that this is a necessary entry point for a CLI as this covers much more functionality than necessary. I described what the minimal program loop is (or should be) for a CLI in [this comment](https://github.com/timhul/ClassicSim/issues/145#issuecomment-588540030), did you encounter issues with this approach?

I have changed my mind regarding this. The steps you are suggesting would be useful to enable higher-level testing.

**Comment by jokal2** [comment]
> I described what the minimal program loop is (or should be) for a CLI in this comment, did you encounter issues with this approach?

No, there are no issues. But that's exactly what it is -- minimal. The majority of the functionality of `GUIControl` has nothing to do with controlling the GUI. It's about controlling the simulation and not the GUI. A CLI would also require loading the saved character XML file to generate a character, buff listing, character talents and gear etc. Then it would need to generate the serialized string and start the simulations. This is all done in `GUIControl` but it's purpose is for a general purpose sim controller.

**Comment by timhul** [comment]
@jokal2 Could you rebase it please?

**Comment by jokal2** [comment]
@timhul Done. It's on top of one of my other PRs, though.

**Comment by timhul** [comment]
Manually pushed this PR, thanks for your contribution!

**Pull request closed without merging**
