### PR TITLE
Add Death Grips

### PR DESCRIPTION
**Pull request by veluria**

### CODE REVIEW

**Comment by timhul** [comment]
Please rebase your pull request to fix the merge conflict.

**Comment by veluria** [comment]
Done.

**Comment by veluria** [comment]
Should I add multiple items in one PR? Makes it easier for me anyway.

**Comment by timhul** [comment]
> For the future: Should I add multiple items in one PR? Makes it easier for me anyway.

I am fine with that, in fact I would prefer it.

**Comment by timhul** [comment]
Thanks for the pull request!

**Pull request merged**
