### PR TITLE
Use correct stats weighting for Paladins

### PR DESCRIPTION
**Pull request by veluria**
Now this wasn't quite correct. :)

### CODE REVIEW

**Comment by veluria** [comment]
>Paladins overall are still left incomplete, especially with no SoR.

Do you think that the results as of now are rather accurate though or not? Because most ret guides will advocate a slow weapon over anything else, due to the limited proc rate of SoC. ClassicSim however shows that weapon DPS and stats are more important, and that a slow axe certainly cannot beat a rather fast sword or mace as a human.

**Comment by timhul** [comment]
Advocating slow weapons for SoC should mostly be for PvP reasons since paladins don't have any instant strikes that can proc SoC or otherwise benefit from a slower weapon (at least currently not in the model).

What I feel is missing is confirmation on SoC proc mechanics (that I'm sure paladins have found by now) as documented [here](https://github.com/timhul/ClassicSim/wiki/Mechanics-Details#seal-of-command-proc), SoC avoidance mechanics (melee rules but can also be resisted at 1% but no partials?) SoR of course, Consecration resists/spell modifiers, etc. etc.

**Comment by veluria** [comment]
> Advocating slow weapons for SoC should mostly be for PvP reasons since paladins don't have any instant strikes that can proc SoC or otherwise benefit from a slower weapon (at least currently not in the model).

It's always about the fact that SoC procs are [limited to 7 PPM](https://www.reddit.com/r/classicwow/comments/c24tq4/paladin_seal_of_command_proc_chance/erhoygi/), and it should thus hit as hard as possible when it does.

**Comment by timhul** [comment]
> It's always about the fact that SoC procs are [limited to 7 PPM](https://www.reddit.com/r/classicwow/comments/c24tq4/paladin_seal_of_command_proc_chance/erhoygi/), and it should thus hit as hard as possible when it does.

Err, yes of course. Temporary (hopefully) lapse of brain on my part! It could be of interest to look further into the damage breakdown to see why the difference is smaller than expected.

**Pull request merged**
